abstract class CasherState{}
  class initState extends CasherState{}
  class ChangeIndex extends CasherState{}
  class ChangeValuee extends CasherState{}
  class ChangeSearchAbilty extends CasherState{}
  class OpenDatabase extends CasherState{}
  class CreateDataBaseSucssesful extends CasherState{}
  class CreateDataBaseError extends CasherState{}
  class GetDataProductsSucssesful extends CasherState{}
  class GetDataSupplayersSucssesful extends CasherState{}
  class GetDataInvoiceSucssesful extends CasherState{}
  class GetDataProductsBaseError extends CasherState{}
  class InsertProductSucssesful extends CasherState{}
  class InsertProductError extends CasherState{}
  class SetState extends CasherState{}
  class InsertValueIntoControlar extends CasherState{}
  class UpdateProducts extends CasherState{}
  class DeleteProducts extends CasherState{}
  class SureItemNotFound extends CasherState{}
  class SureItemFound extends CasherState{}
  class ReturnToPage extends CasherState{}
  class InsertIntoOrder extends CasherState{}
  class DeleteItemOrder extends CasherState{}
  class InsertIntoCashier extends CasherState{}
  class UpdateNumItem extends CasherState{}
  class ChangeSelected extends CasherState{}
  class GetSearchItem extends CasherState{}
